spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=300MB

spring.kafka.bootstrap-servers=localhost:9092

file.upload-dir='/media/gestao-documentos-sistema'

spring.cloud.config.server.git.uri='https://github.com/Ravenport/gestao-documentos.git'